Feature/sign links
emilcote/TaskManager1 pull request #10
Opened 2019-12-04 09:49 UTC by emilcote

2019-12-04 10:51 UTC, av-ast commented on TaskManager/config/puma.rb
> +# port        ENV.fetch('PORT') { 3000 }
Мы не коммитим закоментированный код. Гит хранит все изменения и при необходимости всегда можно вернуться к старому коду.

2019-12-04 11:14 UTC, emilcote commented on TaskManager/config/puma.rb
> +# port        ENV.fetch('PORT') { 3000 }
изменил

2019-12-04 15:22 UTC, Andrew8xx8 requested changes

2019-12-04 15:22 UTC, Andrew8xx8 commented on TaskManager/app/forms/session.rb
> +def validate_credentials
Форматирование опять потрачено здесь

2019-12-04 15:22 UTC, Andrew8xx8 commented on TaskManager/config/puma.rb
> +port ENV.fetch('PORT') { 8080 }
Зачем изменил порт?

2019-12-04 16:12 UTC, emilcote commented on TaskManager/app/forms/session.rb
> +def validate_credentials
исправил

2019-12-04 16:12 UTC, emilcote commented on TaskManager/config/puma.rb
> +port ENV.fetch('PORT') { 8080 }
вернул как было

2019-12-05 13:24 UTC, Andrew8xx8 approved these changes

2019-12-05 13:26 UTC, merged