Feature/api
emilcote/TaskManager1 pull request #19
Opened 2019-12-17 14:19 UTC by emilcote

2019-12-17 20:25 UTC, Andrew8xx8 commented on app/controllers/api/v1/application_controller.rb
> +  helper_method :current_user
Что делает helper_method? Разве он нужен в API?

2019-12-18 04:46 UTC, emilcote commented on app/controllers/api/v1/application_controller.rb
> +  helper_method :current_user
Не нужен в api ,исправил

2019-12-24 09:13 UTC, Andrew8xx8 requested changes

2019-12-24 09:13 UTC, Andrew8xx8 commented on app/controllers/admin/users_controller.rb
> +class Admin::UsersController < Admin::ApplicationController
Этот код не касается API зачем он здесь? Он должен быть уже замержен в develop

2019-12-25 08:21 UTC, closed without merging